apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: clickhouse-secrets
  namespace: clickhouse
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "poc/clickhouse"
        objectType: "secretsmanager"
        jmesPath:
          - path: username
            objectAlias: username
          - path: password
            objectAlias: password
  secretObjects:
    - secretName: clickhouse-auth
      type: Opaque
      data:
        - objectName: username
          key: username
        - objectName: password
          key: password
